language: node_js
node_js: '0.12'
sudo: false
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: ezESiG7JnuSLZc2/PPhOvWUv5BHBCr+g86MsuLLw+S+zz3DUfzWHMQ1g5tUvkeSDTPmfEIX41EnPkaoWtsD3OGO0PGXgseAfA8+6Z4N1rICNZZrhXZB2s6UdwRK1e+0Jol4W3kHmt96BHyN2scLNgJYeWMgSJllVsuPhMTlKBZIXI9u540NH8Nxjl3f2WvoIg64Q1mZvMxkpPbw4xssx6U4HSFE8kTTE6+EFsSxzombFX0cLGjPiJ9QZgGVUk4UkIjyiFLQQDfQlLllCaUpqJ9+qbuCNoMSKA2yty/qyZ8Y+r4OlMberjmBzR9GRLLyXWWcaAfMIgwlRhjtLYIDAUSsGM1iwUWCgyB9maG2IiXuYLSueuMx8DcDwbpUepoDgnqBYnM2AJmT8gcsxqlKYzJpYpHDgZgBlLZQgMXqjrVJHs/Tf9XVcLS6HAn1Ww0OOT01jThfy4gClpAuqLayYexsXOoL+RaFg25E2NzuTtaFWgRfWZgcAeqYNDiUzwun2D4vZ5I+NtdRP0gzpbG2fxhFz05vAqyf1Kp6ZYb17Li3A38dIm6Lsvv3qawAIAgNaZpIZX3f89+uq6jHU8kJy1Iv823JK2Xac3vEz3SHUKJnuXFF0LO07om9AcNEXhP/JrJ617S8nfvDtZRJODMFhz8qQwie+65Ql1I871goBpVs=
env:
  global:
  - secure: Dp/+BDnB9NcaDl6/1dkqoxvC++TZRptV9/C55Hz5h1WHzYVeTvjHTdDaPIwb+IrWiBOVnx0/VHmR4xoBXWxacWzAVBJ+S6Ay2oxTM6oXoEfE8/zPgTFBVilAzXgfjHUaplGfmFOrJpKvFTaIOAqC5OCnquxdUYyLqAmzWlvLPtQI8LtY45S1yltEPyOQMBLKCKtQm50u9KvMTZ0i2mRTJHpvmxN92ZUYkU3CezXhCzIlHfCHmBdk7Wck52D6AdXve9Z2TsLE3vxVSEuIbOxxJ6NuYxV+ReD5Bcc01ZZ2Hu8fy5CyN4+HKZIt3tt4MVOk0Ij9azxUS0eK5m9mre1YPQKze6bU0WaGHC8amSleX8l0RAPVZgC5D5vVSyLc/sZMOofw3aVe57Xc6q80eOd5XoSs1p/QYsbCoOo4xJfC5Rr5jRwBgJNelrvBT5qhXLGBWPxzOvIreAIa5DexfYx67/sm+9FHe+R2fMBKLIX5uHypCtJYOuYBM2UWFenTfWuoIigmdoSUjI6VMbqOEPkuyIoBJUaa+AuTF8rfs94WXZt78hS29U9XYxBjWKj+664lJa9e/K49I6mJSwp2Lk9O+sNyJY482QNuAvqcR90MsSXWa4HAYnMJYz4DDwyY6u2Agxn4mtkGHef8GlV63Yv0G4izFISVa1jNn7/dXY+fDO8=
  - secure: Lafhvn4G0Wp2yAiI+pTqty6C+qLzkhrUwzGESJbm5HZmJvFLmfMDE+p/hNdwL9Pn43kdCZP9ve54gJbLZyMmV9cQ/jsBEF1K9QfgmLOik44/laYNvApFQAmuDaTbiUu/CPtc81EnHmsGyXm1DO3ozm8d+6VOs05Hqs/DebdoTlFny1rwbMFMRRiodfzyjZIYNqPxXu4oSFEGuaVwtfAO1FPcMkQNIANgtU5O9EQs3wf584hdGzmkj3B9M4iiZgw+SIskpxe1Xl+Ln7c5++Jq+B3l60e4mnB7KfgSNGLYQZHbZrp6V864mRm4sFldVjEXLoE7VXBdNsQmtLlnIabUueH3xQdem9ElrvSthpxUOwLGYQvNTbVvCO8hRUDmYCj1nXsD5ct7+oHUUlDz0wEie9TdvWJv6egC+ZQ9MgXihqGlHjtoky8oD40FydcJCqqCD8BxNx7k+bu8snu9dkGbzSRwyoBw8EnT9YstszujXIOvpqfb3O6jNZij1BTN7309eCZPFBdDk2W1PE98uSWzQhW0pPah83G7B4MYDKDDK9ZogEO3LgcAyceazMQYav4uB1zBJzKmcqinlz9QkucC9YaP044xDy/VtpmF0OKmminVAiZBrQrJ0Win/keD0Y5MOMSJ4us+e8e/WESRnA5vJwfCRMz89YfHz1biueC0Smo=
  - EB_REGION=us-east-1
  - EB_APP=scratch-www
  - EB_AWS_BUCKET_NAME=elasticbeanstalk-us-east-1-307680192167
  - SKIP_CLEANUP=true
  - ELASTIC_BEANSTALK_LABEL=${TRAVIS_COMMIT:0:5}
  - BUILD_ARCHIVE=$ELASTIC_BEANSTALK_LABEL.zip
before_deploy:
- zip -qr $BUILD_ARCHIVE .
deploy:
- provider: elasticbeanstalk
  access_key_id: $EB_AWS_ACCESS_KEY_ID
  secret_access_key: $EB_AWS_SECRET_ACCESS_KEY
  bucket_name: $EB_AWS_BUCKET_NAME
  bucket_path: $EB_APP
  zip_file: $BUILD_ARCHIVE
  skip_cleanup: $SKIP_CLEANUP
  region: $EB_REGION
  app: $EB_APP
  env: scratch-www-staging
  on:
    repo: LLK/scratch-www
    branch:
    - develop
    - hotfix/*
    - release/*
- provider: elasticbeanstalk
  access_key_id: $EB_AWS_ACCESS_KEY_ID
  secret_access_key: $EB_AWS_SECRET_ACCESS_KEY
  bucket_name: $EB_AWS_BUCKET_NAME
  bucket_path: $EB_APP
  zip_file: $BUILD_ARCHIVE
  skip_cleanup: $SKIP_CLEANUP
  region: $EB_REGION
  app: $EB_APP
  env: scratch-www-production
  on:
    repo: LLK/scratch-www
    branch: master
